### ISSUE TITLE
Memory binding error with STREAM and RandomAccess

### ISSUE THREAD

**Issue by gautham-ramesh** [pc2/HPCC_FPGA#2]
Hi,
I tried compiling and running the STREAM and RandomAccess benchmarks for the BittWare 520N-MX platform which has a Stratix 10 MX FPGA.
For both benchmarks, configuration options were set to their respective default values.
While running the benchmarks, I receive the following error:
`acl_mem.cpp:333: int acl_bind_buffer_to_device(cl_device_id, cl_mem): Assertion 'mem' failed.`

I couldn't find any resources online to debug this. Please help me with this.

**Comment by Mellich** [comment]
Hi,

the error looks like something is going wrong during buffer allocation on the device. Is this the only error that is shown? It would be helpful to post the whole benchmark output to get a better picture of what is going on.

In general, the default settings are targetting the BittWare 520N board with Stratix 10 GX and might not be suitable for the 520N-MX with HBM2. For this board, you need to explicitly give a buffer location for every buffer using an attribute.  If this attribute is not given, the buffer may be placed to some default HBM bank. Maybe the error occurs because the buffers are all placed in the same bank, which gets out of memory. 

I will focus on STREAM now, but the approach will be very similar for RandomAccess.
My first suggestion would be to reconfigure the project with the following parameter and rebuild the host code:

    cmake .. -DUSE_HBM=Yes

This will tell the host code to set the `CL_MEM_HETEROGENEOUS_INTELFPGA` flag when creating the buffers.
Re-run the benchmark with small input sizes and a single kernel repetition:

    ./STREAM_FPGA_intel -f ... -s 4096 -r 1

If this does not work, please give feedback here. You will need to resynthesize the kernel to use more than one HBM bank.
For functionality you should change the following parameters:
- Make sure to give the correct board name using `FPGA_BOARD_NAME`
- Most important: Use the additional setting `INTEL_CODE_GENERATION_SETTINGS` and set it to the path to the `STREAM/settings/settings.gen.intel.stream_kernels_single.s10mxhbm.py` in the repository. This will add the missing attributes to the OpenCL kernel code. The default naming scheme for the HBM banks is HBM0,HBM1,... make sure that this matches the naming for your BSP. You might find further information in the BSP documentation. Unfortunately, I have no access to the BSP documentation to check this. You can change the naming scheme by editing the named settings file.

So the configuration call would be something like this:

    cmake .. -DUSE_HBM=Yes -DFPGA_BOARD_NAME=... -DINTEL_CODE_GENERATION_SETTINGS=...

To get better performance you might also consider changing the additional parameters:
- Set the number of kernel replications to the number of HBM memory banks with `NUM_REPLICATIONS=32`
- Increase the `DEVICE_BUFFER_SIZE` parameter in powers of two until the report shows good utilization of the BRAM. Maybe 4096 and beyond might be worth a try.
- Set `DEFAULT_ARRAY_LENGTH=268435456` to get array sizes of 1GB to better utilize the available global memory

I hope, I could help you with this. I am not able to test the suggestions on my own so any feedback, if some of the suggestions worked for you or not, is really appreciated!

**Comment by gautham-ramesh** [comment]
Hi,

This is the complete output for the error I had reported initially.

```
General setup:
C++ high resolution clock is used.
The clock precision seems to be 1.00000e+01ns

Selected Platform: Intel(R) FPGA SDK for OpenCL(TM)

Selection summary:
Platform Name: Intel(R) FPGA SDK for OpenCL(TM)
Device Name:   p520_max_m210h : BittWare Stratix 10 MX OpenCL platform (aclbitt_s10mx_pcie0)

FPGA Setup:bin/stream_kernels_single.aocx
Prepared FPGA successfully for global Execution!

Implementation of the STREAM benchmark proposed in the HPCC benchmark suite for FPGA.
Version: 2.4

Summary:
Array Size                    134217728 (5.36871e+08 Byte )
Data Type                     cl_float
Kernel File                   bin/stream_kernels_single.aocx
Kernel Replications           1
Kernel Type                   Single
MPI Ranks                     None
Repetitions                   10
Device                        p520_max_m210h : BittWare Stratix 10 MX OpenCL platform (aclbitt_s10mx_pcie0)

Start benchmark using the given configuration. Generating data...

Generation Time: 2.32912e+01 s

Execute benchmark kernel...

STREAM_FPGA_intel: acl_mem.cpp:333: int acl_bind_buffer_to_device(cl_device_id, cl_mem): Assertion 'mem' failed.
```

Coming to your suggestions, I opted to resynthesize the kernel using the following cmake config:

`cmake ../../STREAM -DDEVICE_BUFFER_SIZE=8192 -DFPGA_BOARD_NAME=p520_max_m210h -DUSE_SVM=No -DNUM_REPLICATIONS=1  -DUSE_HBM=Yes -DINTEL_CODE_GENERATION_SETTINGS=../../STREAM/settings/settings.gen.intel.stream_kernels_single.s10mxhbm.py`

Compiling and running the benchmark with these settings resulted in the same initial error that I've pasted above.

Following this, I set the number of replications to be 32:
`bin/STREAM_FPGA_intel -f bin/stream_kernels_single.aocx -r 32`

This config gave me the following output:
```
-------------------------------------------------------------
General setup:
C++ high resolution clock is used.
The clock precision seems to be 1.00000e+01ns
-------------------------------------------------------------
Selected Platform: Intel(R) FPGA SDK for OpenCL(TM)
-------------------------------------------------------------
Selection summary:
Platform Name: Intel(R) FPGA SDK for OpenCL(TM)
Device Name:   p520_max_m210h : BittWare Stratix 10 MX OpenCL platform (aclbitt_s10mx_pcie0)
-------------------------------------------------------------
-------------------------------------------------------------
FPGA Setup:bin/stream_kernels_single.aocx
Prepared FPGA successfully for global Execution!
-------------------------------------------------------------
Implementation of the STREAM benchmark proposed in the HPCC benchmark suite for FPGA.
Version: 2.4

Summary:
Array Size                    134217728 (5.36871e+08 Byte )
Data Type                     cl_float
Kernel File                   bin/stream_kernels_single.aocx
Kernel Replications           32
Kernel Type                   Single
MPI Ranks                     None
Repetitions                   10
Device                        p520_max_m210h : BittWare Stratix 10 MX OpenCL platform (aclbitt_s10mx_pcie0)

-------------------------------------------------------------
Start benchmark using the given configuration. Generating data...
-------------------------------------------------------------
Generation Time: 2.32908e+01 s
-------------------------------------------------------------
Execute benchmark kernel...
-------------------------------------------------------------
ERROR in OpenCL library detected! Aborting.
/home/UFAD/g.ramesh/HPCC_FPGA/STREAM/src/host/execution_default.cpp:439: CL_INVALID_KERNEL_NAME
An error occured while executing the benchmark:
        std::exception
```

I tried giving smaller inputs: `bin/STREAM_FPGA_intel -f bin/stream_kernels_single.aocx -s 67108864`
Corresponding output:
```
-------------------------------------------------------------
General setup:
C++ high resolution clock is used.
The clock precision seems to be 1.00000e+01ns
-------------------------------------------------------------
Selected Platform: Intel(R) FPGA SDK for OpenCL(TM)
-------------------------------------------------------------
Selection summary:
Platform Name: Intel(R) FPGA SDK for OpenCL(TM)
Device Name:   p520_max_m210h : BittWare Stratix 10 MX OpenCL platform (aclbitt_s10mx_pcie0)
-------------------------------------------------------------
-------------------------------------------------------------
FPGA Setup:bin/stream_kernels_single.aocx
Prepared FPGA successfully for global Execution!
-------------------------------------------------------------
Implementation of the STREAM benchmark proposed in the HPCC benchmark suite for FPGA.
Version: 2.4

Summary:
Array Size                    67108864 (2.68435e+08 Byte )
Data Type                     cl_float
Kernel File                   bin/stream_kernels_single.aocx
Kernel Replications           1
Kernel Type                   Single
MPI Ranks                     None
Repetitions                   10
Device                        p520_max_m210h : BittWare Stratix 10 MX OpenCL platform (aclbitt_s10mx_pcie0)

-------------------------------------------------------------
Start benchmark using the given configuration. Generating data...
-------------------------------------------------------------
Generation Time: 1.16485e+01 s
-------------------------------------------------------------
Execute benchmark kernel...
-------------------------------------------------------------
Each test below will take on the order of 4.76941e+04 microseconds.
-------------------------------------------------------------
WARNING -- The above is only a rough guideline.
For best results, please be sure you know the
precision of your system timer.
-------------------------------------------------------------
Execution Time: 1.09807e+00 s
-------------------------------------------------------------
Validate output...
-------------------------------------------------------------
Failed Validation on array a[], AvgRelAbsErr > epsilon (1.000000e-06)
     Expected Value: 1.153301e+12, AvgAbsErr: 5.497558e+11, AvgRelAbsErr: 4.766804e-01
     For array a[], 67108864 errors were found.
Failed Validation on array b[], AvgRelAbsErr > epsilon (1.000000e-06)
     Expected Value: 2.306601e+11, AvgAbsErr: 6.871948e+10, AvgRelAbsErr: 2.979252e-01
     AvgRelAbsErr > Epsilon (1.000000e-06)
     For array b[], 67108864 errors were found.
Failed Validation on array c[], AvgRelAbsErr > epsilon (1.000000e-06)
     Expected Value: 3.075468e+11, AvgAbsErr: 1.374390e+11, AvgRelAbsErr: 4.468879e-01
     AvgRelAbsErr > Epsilon (1.000000e-06)
     For array c[], 67108864 errors were found.
Validation Time: 2.17977e+01 s
       Function Best Rate MB/s     Avg time s       Min time       Max time
            Add    7.56511e+07    1.08173e-05    1.06450e-05    1.10710e-05
           Copy    2.14029e+07    2.58019e-05    2.50840e-05    2.68280e-05
       PCI read    1.76656e+04    4.64834e-02    4.55861e-02    4.77319e-02
      PCI write    1.71821e+04    4.81254e-02    4.68688e-02    4.91461e-02
          Scale    4.84060e+07    1.16347e-05    1.10910e-05    1.20890e-05
          Triad    7.84058e+07    1.04562e-05    1.02710e-05    1.06270e-05
```

**Comment by Mellich** [comment]
Regarding the first execution:
> Following this, I set the number of replications to be 32:
bin/STREAM_FPGA_intel -f bin/stream_kernels_single.aocx -r 32

This call fails because the host code assumes a bitstream with 32 kernels (the `-r 32` flag) but the bitstream synthesized with the given build configuration does only contain a single kernel.
In the second call, the basic kernel execution seems to work, but the results retrieved from the FPGA are all wrong.
STREAM executes the kernel once before starting the measurements of the reported results. The execution time is reported in the line
> Each test below will take on the order of 4.76941e+04 microseconds.

So, the first execution of the kernel takes 47694 microseconds. All other executions are much faster with 10-20 microseconds although they should take nearly the same time. This is why the reported memory bandwidth is in the TB region for all four operations. Most likely these calls are not executed correctly. I added some additional checks for STREAM in the branch [`add_stream_assertions`](https://github.com/pc2/HPCC_FPGA/tree/add_stream_assertions). Please re-compile the host code with the changes and run the last experiment again. The host should now show an error message if an error is reported from the OpenCL API during the measurements.

**Comment by gautham-ramesh** [comment]
I re-synthesized the binary with the additional checks from [add_stream_assertions](https://github.com/pc2/HPCC_FPGA/tree/add_stream_assertions). I used this confiugration:
`cmake ../../STREAM -DDEVICE_BUFFER_SIZE=2048 -DFPGA_BOARD_NAME=p520_max_m210h -DUSE_SVM=No -DNUM_REPLICATIONS=32 -DUSE_HBM=Yes -DINTEL_CODE_GENERATION_SETTINGS=../../STREAM/settings/settings.gen.intel.stream_kernels_single.s10mxhbm.py` 

I was then able to run both STREAM and RandomAccess without any errors.
Thank you!

**Comment by Mellich** [comment]
Can you elaborate on what exactly was the problem with the two benchmarks? The mentioned branch just added some extra checks but did not change functionality, so the execution should also work with the code provided on the master branch. Did you change something in the host or device code or was it just a misconfiguration?

**Comment by gautham-ramesh** [comment]
I think it was just a misconfiguration. I had to enable the `USE_HBM` flag and set `NUM_REPLICATIONS=32 (4 in the case of RnadomAccess)` ; this is because one can only access HBM through OpenCL on the MX board.

**Comment by Mellich** [comment]
Also for RandomAccess, the number of kernel replications should be chosen according to the number of available memory banks: `NUM_REPLICATIONS=32`. Okay, thank you for your feedback!
