### ISSUE TITLE
Error with buffer creation in FFT benchmark

### ISSUE THREAD

**Issue by gautham-ramesh** [pc2/HPCC_FPGA#3]
Hi,

When the FFT benchmark is configured with NUM_REPLICATIONS > 4, the `make CL_CONTEXT_EMULATOR_DEVICE_INTELFPGA=1 test` command fails with the following message:

> Error: Invalid or unsupported flags
> ERROR in OpenCL library detected! Aborting.
> <root_dir>/FFT/src/host/execution_default.cpp:66: CL_INVALID_VALUE
> An error occured while executing the benchmark: 
> An OpenCL error occured: CL_INVALID_VALUE 

This is the code causing the error:
https://github.com/pc2/HPCC_FPGA/blob/484d9f62acd7d54f3b3a53a655edba4711bf557d/FFT/src/host/execution_default.cpp#L65-L66

The error seems to arise from the flag value, `CL_MEM_WRITE_ONLY | (config.programSettings->useMemoryInterleaving ? 0 : (((2 * r) + 2) << 16))`. I am curious about the purpose of the `((2 * r) + 2) << 16` operation and how it relates to the memory flag.

Any inputs regarding the error and potential ways to fix it will be hugely appreciated.

Thank you.

**Comment by Mellich** [comment]
When you are not using memory interleaving, the host will try to distribute the input and output buffers over the available memory banks. The `((2 * r) + 1) << 16` and `((2 * r) + 2) << 16` are used to calculate the `CL_CHANNEL_X_INTELFPGA` flag, which is defined to be `X << 16` in `cl_ext_intelfpga.h`. Every kernel replication will need *two* memory banks here because the data is streamed through the kernel in a single pipeline: read from one bank and written to the other. 

The error arises because the channel flags are only defined until `CL_CHANNEL_7_INTELFPGA`. I assume you are trying to execute the benchmark for a device with four memory banks. In that case, you have to choose `NUM_REPLICATIONS=2` to utilize all banks. 

EDIT: Maybe also take a look into the `Expected Bottlenecks` section to get a better idea how to set the configuration parameters: https://pc2.github.io/HPCC_FPGA/build/html/FFT/index.html#expected-bottlenecks

**Comment by gautham-ramesh** [comment]
Thank you for the informative response.

I'm trying to run the benchmark on a device with 32 memory banks. So if I've understood it correctly, this is not feasible as I would have to set `NUM_REPLICATIONS=16` but the channel flags are only defined until `CL_CHANNEL_7_INTELFPGA`.

**Comment by Mellich** [comment]
FFT will need some additions in the host and device code to work with Intel HBM. More precisely, the kernel parameters need attributes to specify the target HBM memory bank. Look into the kernel code of the STREAM benchmark [`STREAM/src/device/stream_kernels_single.cl`](https://github.com/pc2/HPCC_FPGA/blob/master/STREAM/src/device/stream_kernels_single.cl) and into [`STREAM/settings/settings.gen.intel.stream_kernels_single.s10mxhbm.py`](https://github.com/pc2/HPCC_FPGA/blob/master/STREAM/settings/settings.gen.intel.stream_kernels_single.s10mxhbm.py). In the host code, you will need to pass another flag for the memory buffers: `CL_MEM_HETEROGENEOUS_INTELFPGA`. Unfortunately, I won't find time soon to do this by myself, but if you are planning to do these changes consider opening a merge request!

**Comment by gautham-ramesh** [comment]
Thank you, I will look into it

**Comment by Mellich** [comment]
I now added support for HBM on Intel devices for FFT and GEMM with the latest commit.
This is again not tested, so please report if this works for you.
Like with the other benchmarks you will need to use the `USE_HBM` flag for the configuration.

**Comment by Mellich** [comment]
Support of Intel HBM for FFT and GEMM was tested successfully for commit eb716f8
